services:
  products:
    build:
      context: .
      dockerfile: ./apps/products/Dockerfile
      target: development
    command: pnpm run start:dev products
    env_file:
      - ./apps/products/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    env_file:
      - .env
    ports:
      - '3306:3306'
